# Generated by Django 5.2 on 2025-05-28 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='analysisrecord',
            old_name='target_type',
            new_name='sample_type',
        ),
        migrations.AddField(
            model_name='analysisrecord',
            name='sample_info',
            field=models.CharField(default=1, max_length=100, verbose_name='样品信息'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='analysisrecord',
            name='size',
            field=models.IntegerField(verbose_name='文件大小(k)'),
        ),
        migrations.AlterField(
            model_name='analysisrecord',
            name='transmission',
            field=models.JSONField(default=list, verbose_name='透射率数据'),
        ),
    ]
