# Generated by Django 5.2 on 2025-06-01 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_analysisrecord_result_alter_analysisrecord_methods'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysisrecord',
            name='file_type',
        ),
    ]
