# Generated by Django 5.2 on 2025-06-01 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0004_remove_analysisrecord_file_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='农药名称')),
                ('positive_value', models.PositiveIntegerField(default=0, verbose_name='阳性总数')),
                ('negative_value', models.PositiveIntegerField(default=0, verbose_name='阴性总数')),
            ],
            options={
                'verbose_name': '总检测情况',
                'verbose_name_plural': '总检测情况',
            },
        ),
    ]
