# Generated by Django 5.2 on 2025-06-01 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetectionStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': '检测统计',
                'verbose_name_plural': '检测统计',
            },
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
