# Generated by Django 5.2 on 2025-06-01 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_detectionstats_delete_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnlineDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=100, unique=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': '在线设备',
                'verbose_name_plural': '在线设备',
            },
        ),
    ]
