# Generated by Django 5.2 on 2025-05-15 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Spectrum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pesticide_name_cn', models.CharField(max_length=50, verbose_name='Pesticide Name Chinese')),
                ('pesticide_name_en', models.CharField(max_length=50, verbose_name='Pesticide Name English')),
                ('pesticide_cas', models.CharField(max_length=20, verbose_name='Pesticide Cas')),
                ('pesticide_molecular_formula', models.CharField(max_length=50, verbose_name='Pesticide Molecular Formula')),
                ('pesticide_remark', models.CharField(max_length=50, verbose_name='Pesticide Remark')),
            ],
        ),
    ]
