# Generated by Django 5.2 on 2025-05-19 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spectral_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spectrum',
            name='pesticide_absorption',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='spectrum',
            name='pesticide_frequency',
            field=models.JSONField(default=list),
        ),
    ]
